### ISSUE TITLE
Incorporate local serving of GA js files into plugin

### ISSUE THREAD

**Issue by nosamttimhcs** [awesomemotive/Google-Analytics-Dashboard-for-WP#140]
It looks like GADWP would conflict with the [CAOS plugin](https://wordpress.org/plugins/host-analyticsjs-local/).  I would like to serve the GA js files from my server, which is what the CAOS plugin will allow, but I don't want to lose the functionality that GADWP provides.

Would you consider including, in your plugin, the local serving and setting of HTTP cache headers for the GA js files?

Thanks!

**Comment by chriscct7** [comment]
We're fully compatible with CAOS now so going to close this issue
