### ISSUE TITLE
Feature request: Add Tracking Code without Access Code

### ISSUE THREAD

**Issue by swinggraphics** [awesomemotive/Google-Analytics-Dashboard-for-WP#157]
I build sites for clients where I do not have access to their Analytics accounts. I like to give them the option to add the dashboard widget, but don't want to require it. I can't just add the tracking code right now, which means I can't use GADWP at all for these sites, and when they get around to wanting the dashboard integration, it means undoing the manual code insertion. (Yes, I could use another plugin, but they all suck compared to GADWP.)

**Comment by chriscct7** [comment]
I'll add this to our feature board.
